### ISSUE TITLE
Task Generate forgejo download url fails even though jmespath is installed

### ISSUE THREAD

**Issue by adrinux** [roles-ansible/ansible_role_gitea#107]
I have jmespath installed:

```
pip3 list
# shows amongst many others
jmespath               1.0.1
```
But the task still fails with:
```
task path: <snip>/ansible_collections/l3d/git/roles/gitea/tasks/set_forgejo_version.yml:51

fatal: [2a01:4f8:c0c:d890::1]: FAILED! => {
    "msg": "You need to install \"jmespath\" prior to running json_query filter"
}
```

This is on Ubuntu server 22.04 Jammy.

I'll take closer look at the role later, but suggestions welcome :)

This obviously means that install fails.

**Comment by Ouack23** [comment]
You _should never_ install Python packages with pip globally :thinking: 

Maybe try to uninstall your package and prefer your distribution native apt package : https://packages.ubuntu.com/jammy/python3-jmespath

This could be totally unrelated to your issue though and I'm sorry if that's the case

**Comment by DO1JLR** [comment]
I have had good experiences running python applications like ansible in a separate venv.

Example:
```
# create venv
python3 -m venv ansible

# enable venv
source ansible/bin/activate

# install ansible
pip3 install ansible-core

# install role l3d.gitea requirements
pip3 install jmespath

# make sure latest version of community.general is available
ansible-galaxy collection install community.general --upgrade
```

Now ``which ansible-playbook`` should point to ``./ansible/bin/ansible-playbook`` from the venv where jmespath is also installed and available.

**Comment by adrinux** [comment]
It was totally unrelated to my issue. I was doing something even more dim and installing jmespath on the server...again, I blame Covid...

Installed python3-jmespath from manjaro's repos on my workstation, works now \o/
