### ISSUE TITLE
Latest releases are not on Galaxy

### ISSUE THREAD

**Issue by abrain** [roles-ansible/ansible_role_gitea#134]
Hi, I noticed, that the newest version on [Ansible Galaxy](https://galaxy.ansible.com/ui/standalone/roles/l3d/gitea/) is v3.3.0. The following patch releases are missing.

I think I found the root cause, PR is incoming.

**Comment by DO1JLR** [comment]
Releasing now partially works again. But to the wrong namespace.

It is currently releasing to https://galaxy.ansible.com/ui/standalone/roles/roles-ansible/gitea/.
I was going to release it to https://galaxy.ansible.com/ui/standalone/roles/l3d/gitea/.

I will have another look at this, but not sure if I will do this before 37c3.
BTW, Uploading the collection works correctly: https://galaxy.ansible.com/ui/repo/published/l3d/git/
