### ISSUE TITLE
service file doesn't get created on centos?

### ISSUE THREAD

**Issue by JensTimmerman** [roles-ansible/ansible_role_gitea#139]
I didn't have time to completely debug this, but when I changed from gitea to forgejo the gitea binary was still used, I first tought that somehow the service template wasn't correctly regenerated for a change like this, since it was already in place, but I now noticed it skips generating the service file at all if the os is not Debian or Suse?

Running on a centos machine.

**Comment by DO1JLR** [comment]
Yes, indeed. There was something with the systemd location in https://github.com/roles-ansible/ansible_role_gitea/commit/12f3c96af08d40733dd16468c52966a4b817d53a

I will have a look
