### ISSUE TITLE
Using `gitea_users` logs passwords

### ISSUE THREAD

**Issue by abrain** [roles-ansible/ansible_role_gitea#170]
When iterating over `gitea_users` to create or remove local users, the full items including the password are logged for both tasks.

While using `loop_control` to only show the user name would look nicer, Ansible recommends to set `no_log: true`: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html#limiting-loop-output-with-label

**Comment by DO1JLR** [comment]
I like the idea with loop_control.

I guess it could look something like that:
```yml
  loop_control:
    label: "user={{ user.name }}"
    loop_var: user
```

But I don't have the time to test it and create  Pull-Request today. @abrain Please feel free to open a PR if you like :kissing_heart:
