### ISSUE TITLE
Galaxy imports stopped at v3.3.0

### ISSUE THREAD

**Issue by bbaassssiiee** [roles-ansible/ansible_role_gitea#175]
https://galaxy.ansible.com/ui/standalone/roles/l3d/gitea/versions/

**Comment by DO1JLR** [comment]
Yes, there is a huge namespace Problem with ansible galany-ng. I currently don't know how to update this role to the l3d space for roles.

You find it at https://galaxy.ansible.com/ui/standalone/roles/roles-ansible/gitea/versions/ vor I recommend the usw AS collection with the ``l3d.git`` collection.

https://galaxy.ansible.com/ui/repo/published/l3d/git/content/role/gitea/

**Comment by bbaassssiiee** [comment]
Works for me.

**roles/requirements.yml:**

```yaml
---
roles:
  - src: roles-ansible.gitea
    name: gitea
```
