### ISSUE TITLE
Codeberg API address changed, Forgejo release tasks now fail

### ISSUE THREAD

**Issue by adrinux** [roles-ansible/ansible_role_gitea#177]
Looks like Codeberg API changed from

```
https://code.forgejo.org/api
```

to

```
https://codeberg.org/api/ etc
```

As a result the role fails at the task "Get specific Forgejo release metadata", unsurprisingly. About to dig in and work up a pull request.

**Comment by adrinux** [comment]
Scratch that. Apparently there is a delay (couple of hours) between a release announcement and the tag being available on code.forgejo.org (and supposedly some discussion about fixing that). So it started working eventually.

Closing this, apologies for the distraction.

**Comment by DO1JLR** [comment]
all good. Thanks for having a look at it @adrinux  :heart:
