### ISSUE TITLE
thomas-maurice / ansible-role-gitea exchangeable with this?

### ISSUE THREAD

**Issue by firesoft-de** [roles-ansible/ansible_role_gitea#24]
Hi,
short question:
Can I swithc the role of thomas-maurice with this role without adjusting variables or is there anything that need a closer look before executing?

**Comment by DO1JLR** [comment]
If you don't defined any of the ``gitea_*_extra_config`` variables and defined the ``gitea_repository_root`` variable then it should work without any trouble. (But I did not tested it)

**Comment by DO1JLR** [comment]
But be warned. Currently the master branch seems to be broken again. https://github.com/thomas-maurice/ansible-role-gitea/issues/96

**Comment by firesoft-de** [comment]
Thanks.
