### ISSUE TITLE
Add 'latest' option for gitea versioning.

### ISSUE THREAD

**Issue by r-pufky** [roles-ansible/ansible_role_gitea#43]
Currently to update versions, you either have to manually specify it in the role with `gitea_version`, or update the the role from galaxy which updates the default value for `gitea_version`. It would be nice to be able to set a `latest` version in the role itself, which checks the installed version versus the version on github source on playbook execution and updates if needed.

Obviously, it should probably come with a warning that updating versions past the currently supported version in the role can lead to errors; but I think the benefit of being able to explicitly say "always keep this at the latest version" outweighs the risk.

**Comment by DO1JLR** [comment]
Yes, I think that's a good idea.

There has already been an issue in this direction: https://github.com/thomas-maurice/ansible-role-gitea/issues/51

However, I have not yet seen an implementation of this idea or built it myself. Maybe you would like to make a pull request for this? I can't promise when I will be able to implement it satisfactorily. So far I just increase the gitea version with every release, after I have tested it locally on my gitea server.
