### ISSUE TITLE
sudo: gitea command not found

### ISSUE THREAD

**Issue by JensTimmerman** [roles-ansible/ansible_role_gitea#74]
gitea is installed in /usr/local/bin, the ' Backing up gitea before upgrade' command calls sudo gitea, which fails
```
[jens@giteaqa ~]$ sudo -u gitea  which gitea
which: no gitea in (/sbin:/bin:/usr/sbin:/usr/bin)


[gitea@giteaqa ~]$ which gitea
/usr/local/bin/gitea
```

This behaviour was introduced in 
https://github.com/roles-ansible/ansible_role_gitea/pull/66

**Comment by DO1JLR** [comment]
thanks for submitting and fixing this issue @JensTimmerman :kissing_heart:

**Comment by JensTimmerman** [comment]
Thank you for keeping this role up to date :)
