### ISSUE TITLE
a backup on upgrade is not made when gitea is not running

### ISSUE THREAD

**Issue by JensTimmerman** [roles-ansible/ansible_role_gitea#78]
https://github.com/roles-ansible/ansible_role_gitea/blob/d33e6b1da8988e9036dfcc4ed97093080e295640/tasks/backup.yml#L32

this can happen e.g. when the backup failed en then the task is ran again, gitea was stopped, no backup was made, gitea was updated.

**Comment by DO1JLR** [comment]
by looking at https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html I guess using the ``rescue`` option to start gitea again could solve the issue.

Or do you prefer deletung the `` - ansible_facts.services["gitea.service"].state == "running" `` condition?

**Comment by JensTimmerman** [comment]
I'm not completely sure on how to approach this, removing the running would probably result in splitting up the entire block, but I think you kind of want the block?

**Comment by DO1JLR** [comment]
Personally, I no longer use the "backup before upgrade" option. And I don't have a strong opinion about how that should look.

If you have an opinion how it should look like, feel free to make a pull request.
